src/Chirp.Web/Pages/AboutMe.cshtml.cs
using System.Globalization;
using System.Text;
using Chirp.Core;
using Chirp.Core.DTOs;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Chirp.Web.Pages;

/// <summary>
/// PageModel for the AboutMe page that shows the information about User including claims, followers, followees and Cheeps.
/// The page allows Users to download their data and delete their account.
/// The AboutMe page is only accessible for authenticated users.
/// </summary>

[Authorize]
public class AboutMeModel : BasePageModel
{
    // Cheeps and Followers
    private readonly ICheepRepository _cheepRepository;
    private readonly IFollowerRepository _followerRepository;
    private readonly IUserRepository _userRepository;
    private readonly IReactionRepository _reactionRepository;
    public IEnumerable<CheepDto> Cheeps { get; set; } = new List<CheepDto>();
    public IEnumerable<UserDto> Followers { get; set; } = new List<UserDto>();
    public IEnumerable<UserDto> Followees { get; set; } = new List<UserDto>();

    // Pagination
    public int CurrentPage { get; set; } = 1;
    public int MaxCheepsPerPage { get; set; } = 32;
    public int TotalPageCount { get; set; }
    public int StartPage { get; set; }
    public int EndPage { get; set; }
    public int DisplayRange { get; set; } = 5;

    // User Claims
    public string? ID { get; set; }
    public string? Username { get; set; }
    public string? Name { get; set; }
    public string? Email { get; set; }
    public string? GithubURL { get; set; }
    public string? Avatar { get; set; }

    public AboutMeModel(ICheepRepository cheepRepository, IFollowerRepository followerRepository, IUserRepository userRepository, IReactionRepository reactionRepository)
    {
        _cheepRepository = cheepRepository;
        _followerRepository = followerRepository;
        _userRepository = userRepository;
        _reactionRepository = reactionRepository;
    }

    public async Task<IActionResult> OnGet()
    {
        if (!await HandleUserAuthenticationAndClaims())
        {
            return Unauthorized();
        }

        if (User.Identity?.IsAuthenticated == true)
        {
            try
            {
                var newUser = new UserDto
                {
                    Name = User.Identity?.Name ?? "Unknown", // Use null conditional operator with null coalescing operator
                    Email = (User.Identity?.Name ?? "Unknown") + "@chirp.com" // Use null conditional operator with null coalescing operator
                };

                await _userRepository.CreateUser(newUser);
            }
            catch (ArgumentException ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        // Fetch cheeps and followers
        if (Username != null)
        {
            //! ChatGPT's parser -  Parse the page parameter
            var pageValues = Request.Query["page"].ToString();
            if (int.TryParse(pageValues, out int parsedPage) && parsedPage > 0)
            {
                CurrentPage = parsedPage;
            }

            Cheeps = await _cheepRepository.GetCheepsFromUser(Username);
            Followers = (await _followerRepository.GetFolloweesFromUser(Username)).OrderBy(u => u.Name).ToList();
            Followees = (await _followerRepository.GetFollowersFromUser(Username)).OrderBy(u => u.Name).ToList();

            // Pagination
            TotalPageCount = await GetTotalPages(Username) == 0 ? 1 : await GetTotalPages(Username);
        }
        await CalculatePagination();

        Cheeps = Cheeps
            .OrderByDescending(c => DateTime.ParseExact(c.TimeStamp, "MM/dd/yyyy HH:mm:ss", CultureInfo.InvariantCulture))
            .Skip((CurrentPage - 1) * MaxCheepsPerPage)
            .Take(MaxCheepsPerPage);

        return await Task.FromResult<IActionResult>(Page());
    }

    public async Task<int> GetTotalPages(string user)
    {
        int totalCheeps = (await _cheepRepository.GetCheepsFromUser(user)).Count();
        return (int)Math.Ceiling((double)totalCheeps / MaxCheepsPerPage);
    }

    public Task CalculatePagination()
    {
        StartPage = Math.Max(1, CurrentPage - DisplayRange / 2);
        EndPage = Math.Min(TotalPageCount, StartPage + DisplayRange - 1);

        if (EndPage - StartPage + 1 >= DisplayRange)
        {
            return Task.CompletedTask;
        }

        if (StartPage > 1)
        {
            StartPage = Math.Max(1, EndPage - DisplayRange + 1);
        }
        else if (EndPage < TotalPageCount)
        {
            EndPage = Math.Min(TotalPageCount, StartPage + DisplayRange - 1);
        }

        return Task.CompletedTask;
    }

    public async Task<IActionResult> OnPostDownloadData()
    {
        if (!await HandleUserAuthenticationAndClaims())
        {
            return Unauthorized();
        }

        // Fetch cheeps and followers
        if (Username != null)
        {
            Cheeps = await _cheepRepository.GetCheepsFromUser(Username);
            Followers = (await _followerRepository.GetFolloweesFromUser(Username)).OrderBy(u => u.Name).ToList();
            Followees = (await _followerRepository.GetFollowersFromUser(Username)).OrderBy(u => u.Name).ToList();
        }

        // Create a string containing user data
        var userData = $"Your user data in Chirp27! \nRetrieved at {DateTime.Now}\n\n";
        userData += new string('_', 75) + $"\n\nClaims: \n\t- ID: {ID} \n\t- Username: {Username} \n\t- Email: {Email} \n\t- Name: {Name} \n\t- GitHub URL: {GithubURL} \n\t- Avatar: {Avatar}\n\n";

        // TODO - reverse names followers and followees?
        // Add followers to the string
        userData += new string('_', 75) + "\n\nFollowing:\n";
        foreach (var follower in Followers)
        {
            userData += $"\t - {follower.Name}\n";
        }
        userData += "\n";

        // Add followees to the string
        userData += new string('_', 75) + "\n\nFollowees:\n";
        foreach (var followee in Followees)
        {
            userData += $"\t - {followee.Name}\n";
        }
        userData += "\n";

        // Add cheeps to the string
        userData += new string('_', 75) + "\n\nCheeps:\n";
        foreach (var cheep in Cheeps)
        {
            userData += $"\t- Username: {cheep.UserName}\n";
            userData += $"\t- Timestamp: {cheep.TimeStamp}\n";
            userData += $"\t- Message: {cheep.Message}\n\n";
        }

        //! ChatGPT
        // Convert user data to bytes
        var fileContent = Encoding.UTF8.GetBytes(userData);

        // Return a FileContentResult with the content and content type
        return new FileContentResult(fileContent, "text/plain")
        {
            FileDownloadName = "Chirp27 - My User Data.txt"
        };
    }
    
    public async Task<IActionResult> OnPostForgetMe()
    {
        if (!await HandleUserAuthenticationAndClaims())
        {
            return Unauthorized();
        }
        
        if (Username is not null)
        {
            Console.WriteLine("Deleting user: " + Username);

            var user = await _userRepository.GetUserByName(Username);
            
            await _userRepository.DeleteUser(user);
        }
        
        await HttpContext.SignOutAsync();
        
        return RedirectToPage("Public");
    }

    private async Task<bool> HandleUserAuthenticationAndClaims()
    {
        if (User.Identity?.IsAuthenticated == false)
        {
            await HandleNotAuthenticated();
            return false;
        }

        // User Claims
        foreach (var claim in User.Claims)
        {
            Console.WriteLine($"Claim Type: {claim.Type}, Claim Value: {claim.Value}");
        }

        ID = User.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")?.Value;
        Username = User.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name")?.Value;
        Email = User.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress")?.Value;
        Name = User.FindFirst("urn:github:name")?.Value;
        GithubURL = User.FindFirst("urn:github:url")?.Value;
        Avatar = $"https://avatars.githubusercontent.com/{Username}";

        return true;
    }
    
    public async Task<IActionResult> OnPostLikeCheep(Guid cheepId, string userName)
    {
        return await HandleLike(cheepId, userName, _reactionRepository);
    }
    public async Task<int> GetLikeCount(Guid cheepId)
    {
        return await HandleGetLikeCount(cheepId, _reactionRepository);
    }

    public async Task<bool> HasUserLikedCheep(Guid cheepId, string userName)
    {
        return await HandleHasUserLikedCheep(cheepId, userName, _reactionRepository);
    }

    public async Task<IActionResult> OnPostLogOut()
    {
        return await HandleLogOut();
    }
}

src/Chirp.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
namespace Chirp.Web.Pages;

/// <summary>
/// PageModel for the Error page that is shown when an error occurs.
/// </summary>

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : BasePageModel
{
    public string? RequestId { get; set; }
    public Task OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        return Task.CompletedTask;
    }
    
    public async Task<IActionResult> OnPostAuthenticateLogin()
    {
        return await HandleAuthenticateLogin();
    }
    
    public async Task<IActionResult> OnPostLogOut()
    {
        return await HandleLogOut();
    }
}

src/Chirp.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;

namespace Chirp.Web.Pages;

/// <summary>
/// PageModel for the Privacy page that shows the privacy policy of the application.
/// Both authenticated and unauthenticated users can access the Privacy page
/// </summary>

public class PrivacyModel : BasePageModel
{
    public async Task<IActionResult> OnPostAuthenticateLogin()
    {
        return await HandleAuthenticateLogin();
    }
    public async Task<IActionResult> OnPostLogOut()
    {
        return await HandleLogOut();
    }
}

src/Chirp.Web/Pages/Public.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Chirp.Core;
using Chirp.Core.DTOs;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;

namespace Chirp.Web.Pages;

/// <summary>
/// PageModel for the Public page that shows the public timeline for all Cheeps.
/// Users can create Cheeps, react to Cheeps and follow other users from the Public page.
/// Both authenticated and unauthenticated users can access the Public page
/// </summary>

public class PublicModel : BasePageModel
{
    private IValidator<CheepDto> _validator;

    private readonly ICheepRepository _cheepRepository;
    private readonly IUserRepository _userRepository;
    private readonly IFollowerRepository _followerRepository;
    private readonly IReactionRepository _reactionRepository;
    public IEnumerable<CheepDto> Cheeps { get; set; } = new List<CheepDto>();
    public int CurrentPage { get; set; } = 1;
    public int MaxCheepsPerPage { get; } = 32;
    public int TotalPageCount { get; set; }
    public int StartPage { get; set; }
    public int EndPage { get; set; }
    public int DisplayRange { get; set; } = 5;
    public int CheepMaxLength { get; set; } = 160;
    public Dictionary<string, bool> FollowStatus { get; set; } = new Dictionary<string, bool>();


    [BindProperty, StringLength(160), Required]
    public string? CheepMessage { get; set; }

    public PublicModel(ICheepRepository cheepRepository, IUserRepository userRepository,
                       IFollowerRepository followerRepository, IReactionRepository reactionRepository, IValidator<CheepDto> validator)
    {
        _cheepRepository = cheepRepository;
        _userRepository = userRepository;
        _followerRepository = followerRepository;
        _reactionRepository = reactionRepository;
        _validator = validator;
    }

    public async Task<ActionResult> OnGet()
    {
        if (User.Identity?.IsAuthenticated == true)
        {
            try
            {
                var newUser = new UserDto
                {
                    Name = User.Identity?.Name ?? "Unknown", // Use null conditional operator with null coalescing operator
                    Email = (User.Identity?.Name ?? "Unknown") + "@chirp.com" // Use null conditional operator with null coalescing operator
                };

                await _userRepository.CreateUser(newUser);
            }
            catch (ArgumentException ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        Cheeps = await _cheepRepository.GetCheepsFromPage(CurrentPage);

        // Set follow status for each cheep user
        if (User.Identity?.IsAuthenticated == true)
        {
            foreach (var cheep in Cheeps)
            {
                var userName = cheep.UserName;
                var followersFromUser = await _followerRepository.GetFollowersFromUser(userName);
                var isFollowing = followersFromUser.Any(follower => follower.Name == User.Identity.Name);

                FollowStatus[userName] = isFollowing;
            }
        }

        //The following if statement has been made with the help of CHAT-GPT
        if (int.TryParse(Request.Query["page"], out int parsedPage) && parsedPage > 0)
        {
            CurrentPage = parsedPage;
        }

        Cheeps = await _cheepRepository.GetCheepsFromPage(CurrentPage);

        TotalPageCount = await GetTotalPages() == 0 ? 1 : await GetTotalPages();
        await CalculatePagination();        

        return Page();
    }

    public async Task<int> GetTotalPages()
    {
        int totalCheeps = (await _cheepRepository.GetCheeps()).Count();
        return (int)Math.Ceiling((double)totalCheeps / MaxCheepsPerPage);
    }

    public Task CalculatePagination()
    {
        StartPage = Math.Max(1, CurrentPage - DisplayRange / 2);
        EndPage = Math.Min(TotalPageCount, StartPage + DisplayRange - 1);

        if (EndPage - StartPage + 1 >= DisplayRange)
        {
            return Task.CompletedTask;
        }

        if (StartPage > 1)
        {
            StartPage = Math.Max(1, EndPage - DisplayRange + 1);
        }
        else if (EndPage < TotalPageCount)
        {
            EndPage = Math.Min(TotalPageCount, StartPage + DisplayRange - 1);
        }

        return Task.CompletedTask;
    }

    public async Task<IActionResult> OnPostCheep()
    {
        return await Cheep(CheepMessage, _validator, _cheepRepository);
    }

    public async Task<IActionResult> OnPostFollow(string userName, string followerName)
    {
        return await HandleFollow(userName, followerName, _followerRepository);

    }
    
    public async Task<IActionResult> OnPostLikeCheep(Guid cheepId, string userName)
    {
        return await HandleLike(cheepId, userName, _reactionRepository);
    }
    
    public async Task<int> GetLikeCount(Guid cheepId)
    {
        return await HandleGetLikeCount(cheepId, _reactionRepository);
    }

    public async Task<bool> HasUserLikedCheep(Guid cheepId, string userName)
    {
        return await HandleHasUserLikedCheep(cheepId, userName, _reactionRepository);
    }
    
    public async Task<IActionResult> OnPostAuthenticateLogin()
    {
        return await HandleAuthenticateLogin();
    }

    public async Task<IActionResult> OnPostLogOut()
    {
        return await HandleLogOut();
    }
}

src/Chirp.Web/Pages/SeedDB.cshtml.cs
using Chirp.Infrastructure;
using Chirp.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Chirp.Web.Pages;

/// <summary>
/// PageModel for the SeedDb page that is used to seed the database with data or clear the database.
/// Only authenticated users with the Admin role can access the SeedDb page.
/// </summary>


// TODO - expand with user manager role - [Authorize(Roles = "Admin")]
[Authorize]
public class SeedDbModel : BasePageModel
{
    private readonly ChirpContext _context;
    
    public SeedDbModel(ChirpContext context)
    {
        _context = context;
    }

    // button for seeding DbInitializer
    public async Task<IActionResult> OnPostSeedDatabase()
    {
        await _context.Database.EnsureDeletedAsync();
        await _context.Database.MigrateAsync();
        DbInitializer.SeedDatabase(_context);
        return RedirectToPage("/Public");
    }

    // button for seeding DbInitializer2 (authors with followers)
    public async Task<IActionResult> OnPostSeedDatabase2()
    {
        await _context.Database.EnsureDeletedAsync();
        await _context.Database.MigrateAsync();
        DbInitializer2.SeedDatabase2(_context);
        return RedirectToPage("/Public");
    }
    
    // button for deleting all data from database (table remains)
    public IActionResult OnPostClearDatabase()
    {
        _context.Database.EnsureDeleted();
        _context.Database.Migrate();
        return RedirectToPage("/Public");
    }
    
    // public async Task<IActionResult> OnGet()
    // {
    //     return await HandleNotAuthenticated();
    // }

    public async Task<IActionResult> OnPostLogOut()
    {
        return await HandleLogOut();
    }
}

src/Chirp.Web/Pages/AboutMe.cshtml
@page
@model Chirp.Web.Pages.AboutMeModel
@{
}

@{
    if (!User.Identity?.IsAuthenticated == true)
    {
        RedirectToPage("/");
    }
}

@*TODO Remove commented code?
@* 
@foreach (var claim in User.Claims)
{
    <p>@claim.Type: <span style="color: crimson">@claim.Value<span/></p> 
} 
*@

<h2>About Me</h2>

<div class="user-info">
    <img src=@Model.Avatar class="claim-img" alt="1">
    <p>
        <span class="label">ID:</span> 
        <span class="">@Model.ID<span/>
    </p>
    <p>
        <span class="label">Username:</span> 
        <span class="">@Model.Username<span/>
    <p>
        <span class="label">Name:</span> 
        <span class="">@Model.Name<span/>
    </p>
    <p>
        <span class="label">Email:</span> 
        <span class="">@Model.Email<span/>
    </p>
    <p>
        <span class="label">GitHub URL:</span> 
        <a href="@Model.GithubURL" target="_blank">@Model.GithubURL</a>
    </p>
</div>

<hr/>

<!-- Followers -->
<partial name="Partials/_FollowersTracker" model="Model"/>

<hr/>

<!-- My Cheeps -->
<h3 class="toggle" onclick="toggleSection('myCheeps')">
    My Cheeps: <span id="myCheepsIcon">&#9650;</span>
</h3>
<div class="" id="myCheeps">
    @if (Model.Cheeps.Any())
    {
        <partial name="Partials/_CheepContext" model="Model"/>
        <partial name="Partials/_Pagination" model="Model"/>
    }
    else
    {
        <em>You have no cheeps so far.</em>
    }
</div>

<hr/>

<!-- Download My Data -->
@* <h3 class="toggle" onclick="toggleSection('downloadData')">
    Download Your Data <span id="downloadDataIcon">&#9650;</span>
</h3> *@
<h3>Download Your Data</h3>
<div class="" id="downloadData">
    <p>Your privacy is important to us, and this feature is designed to empower you with control over your information. </p>
    <div class="end">
        <form method="post">
            <button type="submit" class="seed-btn" asp-page-handler="DownloadData">Download Data</button>
        </form>
    </div>
</div>

<hr/>

<!-- Forget Me -->
@* <h3 class="toggle" onclick="toggleSection('forgetMe')">
    Delete account <span id="forgetMeIcon">&#9650;</span>
</h3> *@
<h3>Delete account</h3>
<div class="" id="forgetMe">
    <p>If you wish to part ways with Chirp!, click the button below to permanently delete your account. 
        Any information about you will be erased, and you will not be able to recover any information once deleted.
    </p>

    <div class="end">
        <form method="post">
            <button type="submit" class="unseed-btn" asp-page-handler="ForgetMe" >Forget Me</button>
        </form>
    </div>
</div>

 <script src="/js/aboutMe.js"></script>

src/Chirp.Web/Pages/Login.cshtml
@page

@using Chirp.Infrastructure.Entities
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


@model Chirp.Web.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{

}
else
{
    <div>
        <form asp-page-handler="AuthenticateLogin"  method="post">
            <button><i class="fab fa-github"></i> Sign in</button>
        </form>
        
        <form asp-page-handler="LogOut"  method="post">
                    <button><i class="fab fa-github"></i> Sign out</button>
                </form>
    </div>
}
</ul>

src/Chirp.Web/Pages/Public.cshtml
@page "/"
@model Chirp.Web.Pages.PublicModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}

<div>
    @if (User.Identity?.IsAuthenticated == true)
    {
        <partial name="Partials/_Textbox"/>
    }

    <header>
        <h2> Public Timeline </h2>
        <span class="display-page"> Page @Model.CurrentPage/@Model.TotalPageCount </span>
    </header>

    @if (Model.Cheeps.Any())
    {
        <partial name="Partials/_CheepContext" model="Model"/>
        <partial name="Partials/_Pagination" model="Model"/>
    }
    else
    {
        <em>There are no cheeps so far.</em>
    }
</div>

src/Chirp.Web/Pages/SeedDB.cshtml
@page
@model Chirp.Web.Pages.SeedDbModel
@{
}

@* TODO - temporary implementation - expand with user manager role *@
@if (!new[] { "PhiVaLo", "Tien197", "PTS404", "HelgeCPH", "ondfisk" }.Contains(User.Identity?.Name))
{
    <h2 id="red">Access Denied</h2>
    <p>Sorry, this page is only accessible to the developer.</p>
    <p>You will be redirected to the home page in <span id="countdown" class="red">5</span> seconds.</p>

    <script src="/js/redirectHome.js"></script>
}
else
{
    <h2>Seed Database</h2>

    <div class="seed-info">
        <h3>
            <i class="fa-solid fa-triangle-exclamation caution"></i>
            Caution
            <i class="fa-solid fa-triangle-exclamation caution"></i>
        </h3>

        <p> This will clear the database and seed it with test data. </p>
        <div class="seed-container">
            <form method="post" asp-page-handler="SeedDatabase" onsubmit="return confirmAction('reset')">
                <button class="seed-btn">Seed DB1</button>
            </form>

            <form method="post" asp-page-handler="SeedDatabase2" onsubmit="return confirmAction('reset')">
                <button class="seed-btn">Seed DB2</button>
            </form>

            <form method="post" asp-page-handler="ClearDatabase" onsubmit="return confirmAction('clear')">
                <button class="unseed-btn">Clear Database</button>
            </form>
        </div>

    </div>
    <ul>
        <li><b>Seed DB1</b>: Seed test data from DbInitializer</li>
        <li><b>Seed DB2</b>: Seed test data from DbInitializer2 (includes author following other authors)</li>
    </ul>

    @*! Alert boxes is fine in production - For UI-Test (Playwright), a slightly different code is needed to trigger this! *@
    @* <script src="/js/seedDB.js"></script> *@
}

src/Chirp.Web/Pages/SeedDb.cshtml
@page
@model Chirp.Web.Pages.SeedDbModel
@{
}

<h2>Seed Database</h2>

<div class="seed-info">
    <h3>
        <i class="fa-solid fa-triangle-exclamation caution"></i>
        Caution
        <i class="fa-solid fa-triangle-exclamation caution"></i>
    </h3>

    <p> This will clear the database and seed it with test data. </p>
    <div class="seed-container">
        <form method="post" asp-page-handler="SeedDatabase" onsubmit="return confirmAction('reset')">
            <button class="seed-btn">Reset Database</button>
        </form>

        <form method="post" asp-page-handler="ClearDatabase" onsubmit="return confirmAction('clear')">
            <button class="unseed-btn">Clear Database</button>
        </form>
    </div>
</div>

@*! temporary todo list *@
<div class="seed-info" style="text-align: left; color: red">
    <ul>
        <li>This page will be restricted to certain users later</li>
    </ul>
</div>

<script src="/js/seedDB.js"></script>

src/Chirp.Web/Pages/UserTimeline.cshtml
@page "/{user}"
@model Chirp.Web.Pages.UserTimelineModel
@{
    ViewData["Title"] = "Chirp!";
    Layout = "Shared/_Layout";
}


<div>
    @if (User.Identity?.IsAuthenticated == true)
    {
        <partial name="Partials/_Textbox"/>
    }

    <!-- Followers -->
    <partial name="Partials/_FollowersTracker" model="Model"/>
    <hr>    

    <header>
        <h2> @Model.RouteName's Timeline </h2>
        <span class="display-page"> Page @Model.CurrentPage/@Model.TotalPageCount </span>
    </header>


    @if (Model.Cheeps.Any())
    {
        <partial name="Partials/_CheepContext" model="Model"/>
        <partial name="Partials/_Pagination" model="Model"/>
    }
    else
    {
        <em>There are no cheeps so far.</em>
    }
</div>

 <script src="/js/aboutMe.js"></script>