src/Chirp.Web/Pages/Public.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Chirp.Core;
using Chirp.Core.DTOs;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;

namespace Chirp.Web.Pages;

/// <summary>
/// PageModel for the Public page that shows the public timeline for all Cheeps.
/// Users can create Cheeps, react to Cheeps and follow other users from the Public page.
/// Both authenticated and unauthenticated users can access the Public page
/// </summary>

public class PublicModel : BasePageModel
{
    private IValidator<CheepDto> _validator;

    private readonly ICheepRepository _cheepRepository;
    private readonly IUserRepository _userRepository;
    private readonly IFollowerRepository _followerRepository;
    private readonly IReactionRepository _reactionRepository;
    public IEnumerable<CheepDto> Cheeps { get; set; } = new List<CheepDto>();
    public int CurrentPage { get; set; } = 1;
    public int MaxCheepsPerPage { get; } = 32;
    public int TotalPageCount { get; set; }
    public int StartPage { get; set; }
    public int EndPage { get; set; }
    public int DisplayRange { get; set; } = 5;
    public int CheepMaxLength { get; set; } = 160;
    public Dictionary<string, bool> FollowStatus { get; set; } = new Dictionary<string, bool>();


    [BindProperty, StringLength(160), Required]
    public string? CheepMessage { get; set; }

    public PublicModel(ICheepRepository cheepRepository, IUserRepository userRepository,
                       IFollowerRepository followerRepository, IReactionRepository reactionRepository, IValidator<CheepDto> validator)
    {
        _cheepRepository = cheepRepository;
        _userRepository = userRepository;
        _followerRepository = followerRepository;
        _reactionRepository = reactionRepository;
        _validator = validator;
    }

    public async Task<ActionResult> OnGet()
    {
        if (User.Identity?.IsAuthenticated == true)
        {
            try
            {
                var newUser = new UserDto
                {
                    Name = User.Identity?.Name ?? "Unknown", // Use null conditional operator with null coalescing operator
                    Email = (User.Identity?.Name ?? "Unknown") + "@chirp.com" // Use null conditional operator with null coalescing operator
                };

                await _userRepository.CreateUser(newUser);
            }
            catch (ArgumentException ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        Cheeps = await _cheepRepository.GetCheepsFromPage(CurrentPage);

        // Set follow status for each cheep user
        if (User.Identity?.IsAuthenticated == true)
        {
            foreach (var cheep in Cheeps)
            {
                var userName = cheep.UserName;
                var followersFromUser = await _followerRepository.GetFollowersFromUser(userName);
                var isFollowing = followersFromUser.Any(follower => follower.Name == User.Identity.Name);

                FollowStatus[userName] = isFollowing;
            }
        }

        //The following if statement has been made with the help of CHAT-GPT
        if (int.TryParse(Request.Query["page"], out int parsedPage) && parsedPage > 0)
        {
            CurrentPage = parsedPage;
        }

        Cheeps = await _cheepRepository.GetCheepsFromPage(CurrentPage);

        TotalPageCount = await GetTotalPages() == 0 ? 1 : await GetTotalPages();
        await CalculatePagination();        

        return Page();
    }

    public async Task<int> GetTotalPages()
    {
        int totalCheeps = (await _cheepRepository.GetCheeps()).Count();
        return (int)Math.Ceiling((double)totalCheeps / MaxCheepsPerPage);
    }

    public Task CalculatePagination()
    {
        StartPage = Math.Max(1, CurrentPage - DisplayRange / 2);
        EndPage = Math.Min(TotalPageCount, StartPage + DisplayRange - 1);

        if (EndPage - StartPage + 1 >= DisplayRange)
        {
            return Task.CompletedTask;
        }

        if (StartPage > 1)
        {
            StartPage = Math.Max(1, EndPage - DisplayRange + 1);
        }
        else if (EndPage < TotalPageCount)
        {
            EndPage = Math.Min(TotalPageCount, StartPage + DisplayRange - 1);
        }

        return Task.CompletedTask;
    }

    public async Task<IActionResult> OnPostCheep()
    {
        return await Cheep(CheepMessage, _validator, _cheepRepository);
    }

    public async Task<IActionResult> OnPostFollow(string userName, string followerName)
    {
        return await HandleFollow(userName, followerName, _followerRepository);

    }
    
    public async Task<IActionResult> OnPostLikeCheep(Guid cheepId, string userName)
    {
        return await HandleLike(cheepId, userName, _reactionRepository);
    }
    
    public async Task<int> GetLikeCount(Guid cheepId)
    {
        return await HandleGetLikeCount(cheepId, _reactionRepository);
    }

    public async Task<bool> HasUserLikedCheep(Guid cheepId, string userName)
    {
        return await HandleHasUserLikedCheep(cheepId, userName, _reactionRepository);
    }
    
    public async Task<IActionResult> OnPostAuthenticateLogin()
    {
        return await HandleAuthenticateLogin();
    }

    public async Task<IActionResult> OnPostLogOut()
    {
        return await HandleLogOut();
    }
}

src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages.Shared;

public class LoginPartialModel : PageModel
{
    public void OnGet()
    {
        {
            if (User.Identity?.IsAuthenticated == true)
            {
                Console.WriteLine(User.Identity.Name);
            }
            else
            {
                Console.WriteLine("Not Authenticated");
            }
        }
    }

    public IActionResult OnPostAuthenticateLogin()
    {
        var props = new AuthenticationProperties
        {
            RedirectUri = Url.Page("/Error"),
        };
        return Challenge(props);
    }

    public IActionResult OnPostLogOut()
    {
        HttpContext.SignOutAsync();
        return RedirectToPage();
    }
}

src/Chirp.Web/Pages/Shared/_NavigationPartial.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chirp.Web.Pages.Shared;

public class NavigationPartialModel : PageModel
{
    public void OnGet()
    {
        {
            if (User.Identity?.IsAuthenticated == true)
            {
                Console.WriteLine(User.Identity.Name);
            }
            else
            {
                Console.WriteLine("Not Authenticated");
            }
        }
    }

    public IActionResult OnPostAuthenticateLogin()
    {
        var props = new AuthenticationProperties
        {
            RedirectUri = Url.Page("/Error"),
        };
        return Challenge(props);
    }

    public IActionResult OnPostLogOut()
    {
        HttpContext.SignOutAsync();
        return RedirectToPage();
    }
}

src/Chirp.Web/Pages/Shared/Partials/_CheepContext.cshtml
<ul id="message-list" class="cheeps">
    @foreach (var cheep in Model.Cheeps)
    {
        <li>
            <div class="cheep-container @(cheep.UserName == "PhiVaLo" || cheep.UserName == "Tien197" ? "admin-glow" : "glow")">
                @* User Avatar *@
                <div class="avatar-container">
                    <img class="avatar @(cheep.UserName == "PhiVaLo" || cheep.UserName == "Tien197" ? "admin-glow" : "")" 
                    src="https://avatars.githubusercontent.com/@(cheep.UserName)" alt="Icon1" />
                </div>

                @* Cheep Context *@
                <div class="left-content">
                    <p id="cheep-content">
                        <strong>
                            <a id="author" href="/@cheep.UserName">@cheep.UserName</a>
                        </strong>
                    </p>
                    <p id="cheep-content">
                        <small class="date">@DateTime.ParseExact(cheep.TimeStamp, "MM/dd/yyyy HH:mm:ss", null).ToString("MM/dd/yyyy")</small><br>
                        <small class="time">@DateTime.ParseExact(cheep.TimeStamp, "MM/dd/yyyy HH:mm:ss", null).ToString("HH:mm:ss")</small>                        
                    </p>
                </div>
                <div class="right-content">
                    <p id="cheep-content" class="cheep-message">
                        @cheep.Message
                    </p>
                </div>

                <div class="overlay-2"></div>
            </div>

            @* Reactions *@
            <div class="reactions-container">

                @* Follower *@
                @if (User.Identity?.IsAuthenticated == true && cheep.UserName != User.Identity.Name)
                {
                    <div>
                        <form method="post" asp-page-handler="Follow" asp-route-UserName="@cheep.UserName" asp-route-followerName="@User.Identity?.Name">
                            @if (Model.FollowStatus.TryGetValue(cheep.UserName, out bool isFollowing) && isFollowing)
                            {
                                <button class="follow-btn unfollow" type="submit">Unfollow</button>
                            }
                            else
                            {
                                <button class="follow-btn follow" type="submit">Follow</button>
                            }
                        </form>
                    </div>
                }
                else
                {
                    <div></div>
                }
                @if (User.Identity?.IsAuthenticated == true)
                {
                    <div class="reactions-right-container">
                        
                        @* Replies *@
                        <div class="reaction-item unimplemented">
                            <button class="reaction-btn unimplemented" title="Reply">
                                <i class="fa-regular fa-comment"></i>
                            </button>
                            <span class="reaction-count">0</span>
                        </div>
                        
                        @* Likes *@
                        <div class="reaction-item">
                            <form method="post" asp-page-handler="LikeCheep" asp-route-cheepID="@cheep.Id" asp-route-userName="@User.Identity?.Name">
                                <button class="reaction-btn likes-btn" title="Like">
                                    @if (await Model.HasUserLikedCheep(cheep.Id, User.Identity?.Name))
                                    {
                                        <i class="fa-heart fa-solid red"></i>
                                    }
                                    else
                                    {
                                        <i class="fa-heart fa-regular grey"></i>
                                    }
                                </button>
                                <span class="reaction-count">@await Model.GetLikeCount(cheep.Id)</span>
                            </form>
                        </div>
                        
                    </div>
                }
                else 
                {
                    <div class="reactions-right-container">
                        
                        @* Replies *@
                        <div class="reaction-item unimplemented">
                            <button class="reaction-btn unimplemented" title="Reply">
                                <i class="fa-regular fa-comment"></i>
                            </button>
                            <span class="reaction-count">0</span>
                        </div>
                        
                        @* Likes *@
                        <div class="reaction-item">
                                <button class="reaction-btn likes-btn unimplemented" title="Like">
                                    <i class="fa-heart fa-regular grey"></i>
                                </button>
                                <span class="reaction-count">@await Model.GetLikeCount(cheep.Id)</span>
                        </div>
                        
                    </div>

                }
            </div>
        </li>
    }
</ul>

src/Chirp.Web/Pages/Shared/Partials/_FollowersTracker.cshtml
@*! Follower and Followee names are reversed... *@

<div class="followers-container">
    <!-- Your Followers -->
    <div class="column">
        <h3 class="toggle" onclick="toggleSection('followers')">
            Following <span id="followersIcon">&#9650;</span>
        </h3>
        <div class="followersDiv" id="followers">
            @foreach (var follower in Model.Followers)
            {
                <p><a class="follow-link" href="/@follower.Name">@follower.Name</a></p>
            }
        </div>
    </div>

    <!-- Your Followees -->
    <div class="column">
        <h3 class="toggle" onclick="toggleSection('followees')">
            Followers <span id="followeesIcon">&#9650;</span>
        </h3>
        <div class="" id="followees">
            @foreach (var followee in Model.Followees)
            {
                <p><a class="follow-link" href="/@followee.Name">@followee.Name</a></p>
            }
        </div>
    </div>
</div>

src/Chirp.Web/Pages/Shared/Partials/_Navbar.cshtml
<nav class="navbar">
    @if (User.Identity?.IsAuthenticated == true) 
    {
        <div>
            <a class='@(Context.Request.Path == "/"        ? "active" : "")' href="/">Home </a>
            <a class='@(Context.Request.Path == "/AboutMe" ? "active" : "")' href="AboutMe">About me</a>
            <a class='@(Context.Request.Path != "/" && 
                        Context.Request.Path != "/AboutMe" &&
                        Context.Request.Path != "/Privacy" && 
                        Context.Request.Path != "/SeedDB" ? "active" : "")' 
                        href="@(User.Identity?.Name)">User timeline</a>
            <a class='@(Context.Request.Path == "/Privacy" ? "active" : "")' href="/Privacy">Privacy</a>
            @if ((new[] { "PhiVaLo", "Tien197", "PTS404", "HelgeCPH", "ondfisk" }).Contains(User.Identity?.Name))
            {
                <a class='@(Context.Request.Path == "/SeedDB"  ? "active" : "")' href="/SeedDB">Seed DB </a>
            }
        </div>
        <div>
            <form asp-page-handler="LogOut" method="post">
                <span>Hello <span class="username"><b>@(User.Identity?.Name)</b></span>!</span>
                <button class='login @(Context.Request.Path == "/#" ? "active" : "")'><i
                        class="fa-solid fa-right-from-bracket"></i> Sign out</button>
            </form>
        </div>
    }
    else
    {
        <div>
            <a class='@(Context.Request.Path == "/"        ? "active" : "")' href="/">Home </a>
            <a class='@(Context.Request.Path == "/Privacy" ? "active" : "")' href="/Privacy">Privacy</a>
        </div>
        <div>
            <form asp-page-handler="AuthenticateLogin" method="post">
                <button class="login"><i class="fab fa-github"></i> Sign in</button>
            </form>
        </div>
    }
</nav>

<script>
    var username = '@User.Identity?.Name';
</script>

<script src="/js/navbar.js"></script>

src/Chirp.Web/Pages/Shared/Partials/_Pagination.cshtml
<ul class="pagination">
    @if (Model.CurrentPage > 1)
    {
        <li class="page-item prev-button">
            <a class="page-link" href="?page=1"><i class="fas fa-angle-double-left"></i></a>
        </li>
        <li class="page-item prev-button">
            <a class="page-link" href="?page=@(Model.CurrentPage - 1)"><i class="fas fa-angle-left"></i></a>
        </li>
    }
    @if (Model.StartPage > 1)
    {
        <li class="page-item disabled">
            <span class="page-link">...</span>
        </li>
    }
    @for (var i = Model.StartPage; i <= Model.EndPage; i++)
    {
        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
            <a class="page-link page-number" href="?page=@i">@i</a>
        </li>
    }
    @if (Model.EndPage < Model.TotalPageCount)
    {
        <li class="page-item disabled">
            <span class="page-link">...</span>
        </li>
    }
    @if (Model.CurrentPage < Model.TotalPageCount)
    {
        <li class="page-item next-button">
            <a class="page-link" href="?page=@(Model.CurrentPage + 1)"><i class="fas fa-angle-right"></i></a>
        <li class="page-item next-button">
            <a class="page-link" href="?page=@Model.TotalPageCount"><i class="fas fa-angle-double-right"></i></a>
        </li>
        </li>
    }
</ul>

<script>
    var currentPage = @Model.CurrentPage;
    var totalPageCount = @Model.TotalPageCount;
</script>

@* <script src="/js/pagination.js"></script> *@

src/Chirp.Web/Pages/Shared/Partials/_Textbox.cshtml
<button class="toggleButton">Write Cheep</button>

<hr/>

<div class="textbox-container">
    <h2>Write Cheep</h2>

    <div class="form-container">
        <form method="post" asp-page-handler="Cheep">
            <div class="form-group">
                <textarea name="CheepMessage" id="text" rows="5" maxlength="@Model.CheepMaxLength" 
                required placeholder="Write your cheep here!"></textarea>
            </div>
            <div class="bottom-container">
                <div>
                    <button type="submit">Cheep!</button>
                </div>
                <div>
                    <p class="char-count">Characters: <span id="char-counter">0</span>/@Model.CheepMaxLength</p>
                </div>
            </div>
        </form>
    </div>
    <hr/>
</div>

<script src="/js/textbox.js"></script>